version: "3.8"
services:
  backend:
    container_name: backend_project
    build:
      context: backend
    volumes:
      - ./backend/:/app
      - ./mnt/:/mnt
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8001:8000
    restart: always

  # frontend:
  #   container_name: frontend_project
  #   build:
  #     context: frontend/
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - ./frontend/:/home/node
  #     - /home/node/node_modules
  #   ports:
  #     - 3001:3000
